### ISSUE TITLE
Shutters not moving despite commands being sent

### ISSUE THREAD

**Issue by familyafriends** [RainerStaude/hass-becker-component-plus-pybecker#28]
Hi Rainer,

we wrote on the homeassistant community forum where you asked me to open an issue here. 
Recap: 

- I deleted every remote that was saved to the shutters except the master remote, according to the instructions and heard clacking sounds as confirmation. 
- I put the shutter into pairing mode and send the pairing command via home assistant. I heard clacking sounds as confirmation. So I assume I paired the shutters with my stick. 
- My recent attempts have been done with "RolladenHWR" on channel 1:5. I have yet to repair all the other shutters to the stick. 

I have never done this before so I hope I can provide all the info you need. 

My config:

 ```
cover:
  - platform: becker
    device: "/dev/ttyACM1"
    filename: "my-centronic-stick.db"
    covers:
      kitchen:
        friendly_name: "RollladenKüche"
        channel: "2:1"
        intermediate_position: off
        travelling_time_up: 22.75
        travelling_time_down: 19.45
        remote_id: "7A1A2:1"
      dining_room:
        friendly_name: "RollladenEZ1"
        channel: "2:2"
        intermediate_position: off
        travelling_time_up: 29.5
        travelling_time_down: 25.25
        remote_id: "7A1A2:2"
      dining_room2:
        friendly_name: "RolladenEZ2"
        channel: "2:3"
        intermediate_position: off
        travelling_time_up: 33.6
        travelling_time_down: 23.75
        remote_id: "7A1A2:3"
      living_room:
        friendly_name: "RollladenWZ"
        channel: "2:4"
        intermediate_position: off
        travelling_time_up: 30
        travelling_time_down: 26.5        
      bedroom:
        friendly_name: "RollladenSZ"
        channel: "1:3"
        intermediate_position: off
        travelling_time_up: 18.65
        travelling_time_down: 18
        remote_id: "7A1A3:1"
      bathroom:
        friendly_name: "RollladenBad"
        channel: "1:4"
        intermediate_position: off
        travelling_time_up: 30
        travelling_time_down: 26.5
        remote_id: "7A1A3:2"
      storage_room:
        friendly_name: "RollladenHWR"
        channel: "1:5"
        intermediate_position: off
        travelling_time_up: 18.65
        travelling_time_down: 17.8  
        remote_id: "7A1A3:3"
        
logger:
  default: info
  logs:
    custom_components.becker: debug
```

my-centronic-stick.db:
`'utf-8' codec can't decode byte 0x82 in position 27: invalid start byte`

examples from my home-assistant.log
`INFO (MainThread) [homeassistant.setup] Setup of domain becker took 0.0 seconds`

`DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] BeckerCommunicator thread started.`

Master remote is being received in multiple instances like this one here:
`DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Received packet: unit_id: 6A29B, channel: 0, command: DOWN, argument: 8, packet: b'\x020000000002010B00000000006A29B0210100004839\x03'`
`DEBUG (Thread-2) [custom_components.becker.rf_device] Received packet for dispatcher`
`DEBUG (MainThread) [custom_components.becker.cover] RollladenEZ1 received a packet from dispatcher`
`DEBUG (MainThread) [custom_components.becker.cover] RollladenEZ1 is travelling from position 100 to 0 in 25.25 seconds`
`DEBUG (MainThread) [custom_components.becker.cover] RollladenEZ1 update ha-state now`
`DEBUG (MainThread) [custom_components.becker.cover] RollladenEZ1 setup update ha-state callback in 25.25 seconds`

Me sending out the command with the stick, where nothing happens:
`DEBUG (MainThread) [custom_components.becker.cover] RollladenHWR is travelling from position 100 to 0 in 17.8 seconds`
`DEBUG (MainThread) [custom_components.becker.cover] RollladenHWR update ha-state now`
`DEBUG (MainThread) [custom_components.becker.cover] RollladenHWR setup update ha-state callback in 17.8 seconds`
`DEBUG (Thread-2) [custom_components.becker.pybecker.becker_helper] Sent packet: unit_id: 1737B, channel: 5, command: DOWN, argument: 0, packet: b'\x020000000002010B00620000001737B021010500402E\x03'`

If there is anything else you need, please let me know and I will try my best to provide the information needed.

Thanks for having a look at this in the first place!!!
Steffen
