### ISSUE TITLE
Unable to pair covers

### ISSUE THREAD

**Issue by rofo68** [RainerStaude/hass-becker-component-plus-pybecker#64]
Hello,

I am very new to the Homeassistant world. Just installed a HA OS in a virtual machine on proxmox last week to switch from iobroker to Homeassistant.
At first I integrated all my devices via integrations. After searching for an integration for my Roto roller shutters, I came across this solution. I currently control the shutters via a Mediola gateway (V6 E) and iobroker, but I liked the solution with the USB stick better. After I bought a USB stick (4035 200 041 0), I wanted to integrate the roller shutters.
Unfortunately, I can't get the pairing to work. I have already tried the following:
- uninstalled and reinstalled the integration several times
- various USB cables as extensions
- tested with the “centronic-py” script
- set up my shuttle PC very close to the shutters

My configuration.yaml looks like this:
```
cover:
  - platform: becker
    device: "/dev/serial/by-id/usb-Becker-Antriebe_GmbH_CDC_RS232_v125_Centronic-if00"
    filename: "/config/custom_components/becker/centronic-stick.db"
    covers:
      buero_nord:
        friendly_name: "Büro Rolladen Nord"
        channel: "1"
      buero_sued:
        friendly_name: "Büro Rolladen Süd"
        channel: "2"
      schlafzimmer:
        friendly_name: "Schlafzimmer Rolladen"
        channel: "3"
        
logger:
  default: info
  logs:
    # This must correspond to the folder name of your /config/custom_components/becker folder
    custom_components.becker: debug
```

After I put the shutter into pairing mode (1 x clack) I triggered pairing several times via action. Also I can't see any effect when I put the USB stick in listening mode, I don't see any output when I press a button on the remote (master).

Is there anything else I can test to see if the USB stick is OK before I have to send it back?
Thanks in advice
Robert
