### ISSUE TITLE
Service "becker.pair" not shown in Home Assistant

### ISSUE THREAD

**Issue by marcelhoelscher** [RainerStaude/hass-becker-component-plus-pybecker#67]
Hello,

I am still very new to the topic of “Home Assistant” and am currently trying to control my Roto roof window shutters via Home Assistant.

I bought the black Centronics stick from Becker, connected it to my Home Assistant computer and also installed the "has-becker-component-plus-pybecker" component.

However, in the step where I am supposed to run the “becker.pair” service, I can't get any further because it is not displayed under “Developer tools”->“Actions” - see screenshot (I entered "Becker" as filter but there is no result list shown):

![Image](https://github.com/user-attachments/assets/72e20aac-cc1e-4336-acbe-03b0ab01d4b4)

The integration seems to be installed correctly: I see entities related to the integration and I don't see any errors in the Home Assistant log either.

Below is my “configuration.yaml”:

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Becker Centronic Integration
cover:
  - platform: becker 
    device: "/dev/serial/by-id/usb-Becker-Antriebe_GmbH_CDC_RS232_v125_Centronic-if00"
    filename: "centronic-stick.db"
    covers:
      dachgeschoss_strasse:
        friendly_name: "Dachgeschoss Strasse"
        channel: "1"
      dachgeschoss_garage:
        friendly_name: "Dachgeschoss Garage"
        channel: "2"
```

Here is the output from the Home Assistant log:

```
2025-05-06 16:10:16.473 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration becker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-05-06 16:10:19.458 WARNING (MainThread) [custom_components.becker.rf_device] Filename centronic-stick.db does not exist. Create a new file.
2025-05-06 16:10:19.489 WARNING (MainThread) [custom_components.becker.pybecker.becker] Unit 1 of Dachgeschoss Strasse with channel 1 not registered in database file /config/centronic-stick.db!
```

I have installed the following versions:
Core: 2025.4.4
Supervisor: 2025.04.1
Operating System: 15.2
Frontend: 20250411.0

The Home Assistant runs on a Proxmox system.

Translated with DeepL.com (free version)
